=== ensdomains/ensdomains-landing/src/utils/blog/schema.json
{
  "$schema": "http://json-schema.org/draft-07/schema#",
  "type": "object",
  "properties": {
    "slug": {
      "type": "string",
      "description": "Slug of the post"
    },
    "cover": {
      "type": "string",
      "description": "Cover Image of the post"
    },
    "title": {
      "type": "string",
      "description": "Title of the post"
    },
    "description": {
      "type": "string",
      "description": "Description of the post"
    },
    "date": {
      "type": "string",
      "description": "Date of the post",
      "default": ""
    },
    "tags": {
      "type": "array",
      "items": {
        "type": "string"
      },
      "description": "Tags for the post",
      "default": []
    },
    "authors": {
      "type": "array",
      "items": {
        "type": "string"
      },
      "description": "ENS Names of the authors"
    },
    "youtube": {
      "type": "string",
      "description": "YouTube video ID"
    },
    "draft": {
      "type": "boolean",
      "description": "Draft status of post",
      "default": false
    }
  },
  "required": ["slug", "title", "description", "authors"],
  "additionalProperties": false
}

=== ensdomains/ensdomains-landing/posts/006_ens_at_ethcc5/meta.json
{
    "slug": "ethcc5",
    "title": "ENS at EthCC5",
    "description": "I have attended EthCC every year since 2017 (when it was still called EDCON) and I am glad to be able to come back to Paris again with alisha.eth and lucemans.eth.",
    "date": "2022-06-27",
    "tags": [],
    "authors": ["matoken.eth"]
}

=== ensdomains/ensdomains-landing/posts/032_breaking_down_ens/meta.json
{
  "slug": "breaking-down-ens",
  "title": "Breaking Down ENS (With Less Crypto Jargon)",
  "description": "ENS exists to simplify blockchain addresses and make crypto understandable and accessible to everyone.",
  "date": "2025-03-21",
  "tags": ["education", "subnames"],
  "authors": ["wesd.eth"]
}

=== ensdomains/ensdomains-landing/posts/009_reprogram_ens_cards/meta.json
{
    "slug": "reprogram-ens-cards",
    "title": "Reprogramming Your ENS Card",
    "description": "A guide on setting up and issuing POAPS with an IYK NFC card associated with an ENS name",
    "date": "2023-08-11",
    "tags": ["ENS Cards", "Guide"],
    "authors": ["luc.eth", "zadok7.eth"],
    "draft": true
}

=== ensdomains/ensdomains-landing/posts/017_documentation_update/meta.json
{
    "slug": "documentation-update-1",
    "cover": "https://img.youtube.com/vi/GwX_m28SSOA/0.jpg",
    "title": "Updating the ENS Documentation",
    "description": "The ENS Documentation is receiving an upgrade to its documentation featuring a new look and feel, improved navigation, and a full content rewrite.",
    "date": "2024-02-20",
    "youtube": "GwX_m28SSOA",
    "tags": ["youtube"],
    "authors": ["luc.eth"]
}

=== ensdomains/ensdomains-landing/posts/019_dot_box/meta.json
{
    "slug": "ens-integrates-dot-box",
    "title": "ENS Labs Unveils Integration with .box Domains: A New Era for Web3 Identities",
    "description": "ENS Labs has partnered with Intercap to bring .box domains to the ENS Manager App",
    "date": "2024-04-23",
    "tags": [],
    "authors": ["my.box", "enslabs.eth"]
}

=== ensdomains/ensdomains-landing/posts/035_multi-delegate/meta.json
{
    "slug": "multi-delegate-manager",
    "title": "ENS Labs Introduces the Multi-Delegate Manager to Increase Voting Participation in DAOs",
    "description": "With MDM, ENS token holders can easily delegate their voting power to multiple delegates without splitting up their tokens.",
    "date": "2025-03-28",
    "tags": [],
    "authors": ["enslabs.eth"]
}

=== ensdomains/ensdomains-landing/posts/040_gemini_smart_wallet/meta.json
{
  "slug": "gemini-smart-wallet",
  "title": "Gemini Simplifies Smart Wallet Naming and Recovery with ENS",
  "description": "Geminiâ€™s new self-custodial smart wallet comes with built-in gemini.eth subnames, providing a unique name for every user.",
  "date": "2025-08-14",
  "tags": ["integrations"],
  "authors": ["enslabs.eth"]
}

=== ensdomains/ensdomains-landing/posts/047_hacker_culture/meta.json
{
  "slug": "hacker-culture",
  "title": "Minding the Decentralized Gap: Why Hackers Shouldn't Dismiss the Crypto Movement",
  "description": "urbelis.eth explores the roots and shared values of the hacker and blockchain communities, and why now is the time to bridge the divide and build privacy-preserving technology together. How cypherpunk ideals and hacker culture are thriving in the Ethereum ecosystem.",
  "date": "2025-11-13",
  "tags": ["education", "events"],
  "authors": ["urbelis.eth"]
}
