=== ensdomains/ensdomains-landing/src/utils/blog/schema.json
{
  "$schema": "http://json-schema.org/draft-07/schema#",
  "type": "object",
  "properties": {
    "slug": {
      "type": "string",
      "description": "Slug of the post"
    },
    "cover": {
      "type": "string",
      "description": "Cover Image of the post"
    },
    "title": {
      "type": "string",
      "description": "Title of the post"
    },
    "description": {
      "type": "string",
      "description": "Description of the post"
    },
    "date": {
      "type": "string",
      "description": "Date of the post",
      "default": ""
    },
    "tags": {
      "type": "array",
      "items": {
        "type": "string"
      },
      "description": "Tags for the post",
      "default": []
    },
    "authors": {
      "type": "array",
      "items": {
        "type": "string"
      },
      "description": "ENS Names of the authors"
    },
    "youtube": {
      "type": "string",
      "description": "YouTube video ID"
    },
    "draft": {
      "type": "boolean",
      "description": "Draft status of post",
      "default": false
    }
  },
  "required": ["slug", "title", "description", "authors"],
  "additionalProperties": false
}

=== ensdomains/ensdomains-landing/posts/005_post_mortem_null_byte_vulnerability/meta.json
{
    "slug": "null-byte-vulnerability",
    "title": "Null byte vulnerability in ENS subgraph Postmortem",
    "description": "In April 2022, we were informed of a vulnerability in our subgraph implementation by community contributor lcfr",
    "date": "2023-02-03",
    "tags": ["postmortem"],
    "authors": ["nick.eth"]
}

=== ensdomains/ensdomains-landing/posts/048_celonames_powered_by_ens/meta.json
{
  "slug": "celonames-powered-by-ens",
  "title": "Celonames, powered by ENS",
  "description": "Celonames, powered by ENS, are a new identity layer for people to send, receive, and build on Celo. They feature a unique privacy-preserving method for proving users are real people. ",
  "date": "2025-11-12T18:00:00.000Z",
  "tags": ["subnames", "identity"],
  "authors": ["enslabs.eth"]
}

=== ensdomains/ensdomains-landing/posts/000_template_blog_post/meta.json
{
    "slug": "template",
    "cover": "https://mirror-media.imgix.net/publication-images/ixUWm-C6FTIi4Tg6IQ3Z8.jpeg?height=600&width=1200&h=600&w=1200&auto=compress",
    "title": "Template Blog Post",
    "description": "This is a template blog post.",
    "date": "2023-08-28",
    "tags": ["template"],
    "authors": ["luc.eth"],
    "draft": true
}

=== ensdomains/ensdomains-landing/posts/yt_town_hall_2023_q2/meta.json
{
    "slug": "town-hall-2023-Q2",
    "cover": "https://img.youtube.com/vi/iKXtWaVn-tM/0.jpg",
    "title": "ENS Town Hall Q2 2023",
    "description": "Join us for the ENS Town Hall for Q2 2023! Streamed on Thursday, June 29, 2023.",
    "date": "2023-06-29",
    "tags": ["youtube", "town_hall"],
    "authors": ["alisha.eth"],
    "youtube": "iKXtWaVn-tM"
}

=== ensdomains/ensdomains-landing/posts/051_google_bigquery_community_dataset/meta.json
{
  "slug": "google-bigquery-community-dataset",
  "title": "ENS community dataset on Google Cloud BigQuery",
  "description": "ENS is launching a community dataset on Google Cloud's BigQuery, allowing anyone to analyze ENS activity with SQL within seconds.",
  "date": "2026-01-15",
  "tags": ["education", "data", "google"],
  "authors": ["enslabs.eth"]
}

=== ensdomains/ensdomains-landing/posts/033_fluidkey/meta.json
{
  "slug": "private-transactions-with-fluidkey",
  "title": "Private ENS Transactions With Fluidkey",
  "description": "Fluidkey is a great option if you want to send or receive funds without leaking an accountâ€™s transaction history.",
  "date": "2025-03-25",
  "tags": ["privacy", "integrations"],
  "authors": ["jamesbeck.eth"]
}

=== ensdomains/ensdomains-landing/posts/045_ens_app_explorer_introduction/meta.json
{
  "slug": "ens-app-explorer-introduction",
  "title": "ENS Evolves: Introducing Purpose-Built Tools for Every User",
  "description": "ENS evolves with two purpose-built tools for every user - introducing ENS App for seamless identity management and ENS Explorer for advanced visibility and control. ENSv2 represents our commitment to meeting every user where they are, whether they're taking their first steps into web3 identity or building the infrastructure that will onboard the next billion users.",
  "date": "2025-10-28",
  "tags": ["ens-v2", "design"],
  "authors": ["erni.eth"]
}

=== ensdomains/ensdomains-landing/posts/042_orange_domains/meta.json
{
  "slug": "locker-domains",
  "title": "Orange Domains brings .locker domains to Ethereum with ENS",
  "description": "DNS domain registry Orange Domains has claimed its gTLD .locker within the ENS protocol, giving its users direct access to the Ethereum ecosystem with their existing domains.",
  "date": "2025-09-04",
  "tags": ["dns"],
  "authors": ["enslabs.eth"]
}
